<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\audio.png" />
    <None Remove="Images\banner.jpg" />
    <None Remove="Images\MicButton.png" />
    <None Remove="Images\Wave.png" />
    <None Remove="Images\window.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\audio.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\banner.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\MicButton.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Wave.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\window.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <None Include="Driver\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BunLabs.NAudio.Flac" Version="2.0.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NVorbis" Version="0.10.5" />
  </ItemGroup>

</Project>
